export default {
    k8sPodList: 'http://localhost:9090/api/k8s/pods',
    k8sPodDetail: 'http://localhost:9090/api/k8s/pod/detail',
    k8sPodUpdate: 'http://localhost:9090/api/k8s/pod/update',
    k8sPodDel: 'http://localhost:9090/api/k8s/pod/del',
    k8sPodContainer: 'http://localhost:9090/api/k8s/pod/container',
    k8sPodLog: 'http://localhost:9090/api/k8s/pod/log',
    k8sPodNumNp: 'http://localhost:9090/api/k8s/pod/numnp',
    k8sPvcList: 'http://localhost:9090/api/k8s/pvcs',
    k8sPvcDetail: 'http://localhost:9090/api/k8s/pvc/detail',
    k8sPvcUpdate: 'http://localhost:9090/api/k8s/pvc/update',
    k8sPvcDel: 'http://localhost:9090/api/k8s/pvc/del',
    k8sNodeList: 'http://localhost:9090/api/k8s/nodes',
    k8sNodeDetail: 'http://localhost:9090/api/k8s/node/detail',
    k8sNamespaceList: 'http://localhost:9090/api/k8s/namespaces',
    k8sNamespaceDetail: 'http://localhost:9090/api/k8s/namespace/detail',
    k8sNamespaceDel: 'http://localhost:9090/api/k8s/namespace/del',
    k8sPvList: 'http://localhost:9090/api/k8s/pvs',
    k8sPvDetail: 'http://localhost:9090/api/k8s/pv/detail',
}